# Generated by Django 6.0.5 on 2026-05-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_token',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
